Models/ErrorViewModel.cs
namespace AppJhoBella.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using AppJhoBella.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppJhoBella.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Lembretes()
        {
            return View();
        }

        public IActionResult Filmes()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using AppJhoBella.ApiUsuario.Data.Dto;
using AppJhoBella.ApiUsuario.Services;
using Microsoft.AspNetCore.Mvc;

namespace AppJhoBella.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private UsuarioService _usuarioService;


        public async Task<IActionResult> Login(LoginUsuarioDto dto)
        {
            if (!ModelState.IsValid) return ViewLogin();


            await _usuarioService.Login(dto);
            return Redirect("/Home/Lembretes");
        }

        public IActionResult ViewLogin()
        {
            return View();
        }
        public LoginController(UsuarioService usuarioService, ILogger<HomeController> logger)
        {
            _usuarioService = usuarioService;
            _logger = logger;
        }
    }
}

Controllers/RegistroController.cs
using AppJhoBella.ApiUsuario.Data.Dto;
using AppJhoBella.ApiUsuario.Services;
using AppJhoBella.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace AppJhoBella.Controllers
{
    public class RegistroController : Controller
    {
        private UsuarioService _usuarioService;
        private  ILogger<RegistroController> _logger;

        public async Task<IActionResult> CadastraUsuario(CreateUsuarioDto dto)
        {
            if(!ModelState.IsValid) return Registro();

            await _usuarioService.Cadastro(dto);
            return Redirect("/Login");
        }
        public IActionResult Registro()
        {
            return View();
        }

        public void RedirectToLogin()
        {
            Redirect("/Login");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        public RegistroController(UsuarioService usuarioService, ILogger<RegistroController> logger, HttpClient httpClient)
        {
            _usuarioService = usuarioService;
            _logger = logger;
        }

    }
}

Views/Home/Filmes.cshtml
@{
    ViewData["Title"] = "Filmes";
}
<h1>Página de @ViewData["Title"] em manutenção</h1>

Views/Home/Lembretes.cshtml
@{
    ViewData["Title"] = "Lembretes";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/Lembretes.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/c411e7e344.js" crossorigin="anonymous"></script>
    

</head>
<body>
    <div class="container">
        <div id="lembrete" class="lembrete">
            <div style="margin-top: 15px">
                <label for="exampleFormControlTextarea1" class="form-label"> Adicionar Lembrete</label>
                <textarea class="form-control" id="txtLembrete" rows="3"></textarea>
                <button id="btnAdicionarLembrete">
                    <i class="fa-solid fa-plus"></i>
                    </button>
            </div>
        </div>
    </div>
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action">Lembretess</a>


        <a href="#" class="list-group-item list-group-item-action list-group-item-primary">Lembrete 1</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-secondary">Lembrete 1</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-success">Lembrete 1</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-danger">Lembrete 1</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-warning">Lembrete 1</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-info">Lembrete 1</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-light">Lembrete 1</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-dark">Lembrete 1</a>
    </div>
</body>
</html>

Views/Login/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/Login.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/c411e7e344.js" crossorigin="anonymous"></script>

</head>

<body>
    <div class="container">
        <h2>Login</h2>
        <form method="post">
            <div class="form-group">
                <label for="usuario">Usuário:</label>
                <input type="text" id="usuario" name="usuario" placeholder="Insira o login">
            </div>
            <div class="form-group">
                <label for="senha">Senha:</label>
                <input type="password" id="senha" name="senha" placeholder="Insira a senha" />
            </div>
            <div class="form-group">
                <input type="submit" asp-action="Login" value="Entrar">
            </div>
            <div class="form-group">
                <button type="submit" id="btnRegistrar" asp-controller="Registro" asp-action="Registro"> Registrar </button>
            </div>
        </form>
    </div>
</body>
</html>

Views/Registro/Registro.cshtml
@{
    Layout = null; 
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Registro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Registro.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/c411e7e344.js" crossorigin="anonymous"></script>
    <script>
        function redirectToLogin() 
                { window.location.href = '/Login'; }
    </script>
</head>

<body>
    <div class="container">
        <button class="btnVoltar" id="btnVoltar" onclick="redirectToLogin()"> 
            <i class="fa-solid fa-arrow-rotate-left"></i>
        </button>
        <h2>Registro</h2>
        <form method="post" asp-action="CadastraUsuario">
            <div class="form-group">
            <label for="Usuario">Nome:</label>
            <input type="text" id="Usuario" name="UserName" required>
            </div>

            <div class="form-group">
                <label for="Email">Email:</label>
                <input type="email" id="email" name="email" required>
            </div>

            <div class="form-group">
                <label for="Senha">Senha:</label>
                <input type="password" id="senha" name="senha" required>
            </div>

            <div class="form-group">
                <label for="ConfirmaSenha">Confirme a senha:</label>
                <input type="password" id="ConfirmaSenha" name="ConfirmaSenha" required>
            </div>
            <div class="form-group">
                <label for="DataNascimento">Data de Nascimento:</label>
                <input type="date" id="DataNascimento" name="DataNascimento" required>
            </div>
            <div class="form-group">
            <button type="submit" >Registrar</button>
            </div>
        </form>
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppJhoBella</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppJhoBella.styles.css" asp-append-version="true" />
    <script>
        function redirectToLogin() { window.location.href = '/Login'; }
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3" id="navbar">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Lembretes">Imagem do app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Lembretes">Lembretes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Filmes">Filmes</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <button id="btnSair" type="button" class="nav-link" onclick="redirectToLogin()">
                        <i class="fa-solid fa-right-from-bracket"></i>
                    </button>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AppJhoBella
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    @await RenderSectionAsync("Scripts", required: false)
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Deseja realmente sair?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                    <button type="button" class="btn btn-primary">Sim</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>